### ISSUE TITLE
KeyError: 'bpy_prop_collection[key]: key "Surface" not found'

### ISSUE THREAD

**Issue by pelednoam** [dairin0d/enhanced-3d-cursor#5]
Hey,
I'm trying to use your addon on Blender 2.79, but I keep getting this error:

Traceback (most recent call last):
  File "/homes/5/npeled/.config/blender/2.79/scripts/addons/space_view3d_enhanced_3d_cursor.py", line 5304, in draw_callback_view
    tfm_operator.draw_3d(context)
  File "/homes/5/npeled/.config/blender/2.79/scripts/addons/space_view3d_enhanced_3d_cursor.py", line 988, in draw_3d
    self.get_normal_params(tfm_opts, dest_point)
  File "/homes/5/npeled/.config/blender/2.79/scripts/addons/space_view3d_enhanced_3d_cursor.py", line 1396, in get_normal_params
    surf_matrix = self.csu.get_matrix("Surface")
  File "/homes/5/npeled/.config/blender/2.79/scripts/addons/space_view3d_enhanced_3d_cursor.py", line 1927, in get_matrix
    matrix = self.tou.get_matrix(name)
  File "/homes/5/npeled/.config/blender/2.79/scripts/addons/space_view3d_enhanced_3d_cursor.py", line 2014, in get_matrix
    matrix = self.get_custom(name).matrix.copy()
  File "/homes/5/npeled/.config/blender/2.79/scripts/addons/space_view3d_enhanced_3d_cursor.py", line 2035, in get_custom
    self.scene, name, Matrix())
  File "/homes/5/npeled/.config/blender/2.79/scripts/addons/space_view3d_enhanced_3d_cursor.py", line 2051, in create_transform_orientation
    tfm_orient = scene.orientations[-1]
IndexError: bpy_prop_collection[-1]: out of range.
Traceback (most recent call last):
  File "/homes/5/npeled/.config/blender/2.79/scripts/addons/space_view3d_enhanced_3d_cursor.py", line 2032, in get_custom
    return self.scene.orientations[name]
KeyError: 'bpy_prop_collection[key]: key "Surface" not found'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/5/npeled/.config/blender/2.79/scripts/addons/space_view3d_enhanced_3d_cursor.py", line 5304, in draw_callback_view
    tfm_operator.draw_3d(context)
  File "/homes/5/npeled/.config/blender/2.79/scripts/addons/space_view3d_enhanced_3d_cursor.py", line 988, in draw_3d
    self.get_normal_params(tfm_opts, dest_point)
  File "/homes/5/npeled/.config/blender/2.79/scripts/addons/space_view3d_enhanced_3d_cursor.py", line 1396, in get_normal_params
    surf_matrix = self.csu.get_matrix("Surface")
  File "/homes/5/npeled/.config/blender/2.79/scripts/addons/space_view3d_enhanced_3d_cursor.py", line 1927, in get_matrix
    matrix = self.tou.get_matrix(name)
  File "/homes/5/npeled/.config/blender/2.79/scripts/addons/space_view3d_enhanced_3d_cursor.py", line 2014, in get_matrix
    matrix = self.get_custom(name).matrix.copy()
  File "/homes/5/npeled/.config/blender/2.79/scripts/addons/space_view3d_enhanced_3d_cursor.py", line 2035, in get_custom
    self.scene, name, Matrix())
  File "/homes/5/npeled/.config/blender/2.79/scripts/addons/space_view3d_enhanced_3d_cursor.py", line 2051, in create_transform_orientation
    tfm_orient = scene.orientations[-1]
IndexError: bpy_prop_collection[-1]: out of range.

Thanks!

**Comment by dairin0d** [comment]
Huh. Seems like it fails to create a transform orientation, which is pretty weird.
Does this happen in any .blend file, or in specific ones? Are you using a fresh install of Blender, or there are extra addons / changed settings? If the error still appears in the vanilla ("factory settings") Blender, please provide the instructions on how to reproduce it. If there is no error in the default Blender, then we'll have to figure out which of your installed addons/customizations conflicts with my addon.
