### ISSUE TITLE
Error when view is locked to object

### ISSUE THREAD

**Issue by alanscodelog** [dairin0d/enhanced-3d-cursor#6]
I get the following error whenever I try to set the 3D cursor if the view is locked to an object.

```python
Traceback (most recent call last):
  File "C:\Users\Alan\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\space_view3d_enhanced_3d_cursor.py", line 272, in invoke
    self.vu.set_position(self.vu.get_position(), True)
  File "C:\Users\Alan\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\space_view3d_enhanced_3d_cursor.py", line 2165, in get_position
    obj, bone = self._get_lock_obj_bone()
  File "C:\Users\Alan\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\space_view3d_enhanced_3d_cursor.py", line 2145, in _get_lock_obj_bone
    return obj, bone
UnboundLocalError: local variable 'bone' referenced before assignment

location: <unknown location>:-1
```

I'm not 100% sure what's going on and I'm new to Blender/Python scripting but it seems like at around line [#2135](https://github.com/dairin0d/enhanced-3d-cursor/blob/master/space_view3d_enhanced_3d_cursor.py#L2135) if v3d.lock_bone isn't defined there is no else to set the bone variable. I made a [fork](https://github.com/AlansCodeLog/enhanced-3d-cursor) with a quick fix, just added an `else: bone = None`, and everything seems to be working fine now, but I'm not sure that's the correct way to fix it.

**Comment by dairin0d** [comment]
Thanks! I added your fix.
